name: APISecurity
description: 'Security API action'
cli_alias: 'api-security'
cmd_group: 'assembly'
rest_endpoint: '/mgmt/config/{domain}/APISecurity'
attributes:
  - name: Id
    tf_name: id
    path: name
    type: String
    required: true
    example: 'APISecurity_name'
    description: 'Name of the object. Must be unique among object types in application domain.'
  - name: AppDomain
    tf_name: app_domain
    type: String
    required: true
    example: 'test_domain'
    description: 'The name of the application domain the object belongs to'
  - name: UserSummary
    type: String
    description: 'Comments'
    cli_alias: summary
  - name: Title
    type: String
    description: 'Title'
    cli_alias: title
  - name: CorrelationPath
    type: String
    description: 'Correlation path'
    cli_alias: correlation-path
