name: DmRateLimitConfigurationNameValuePair
model_only: true
list_item: true
attributes:
- name: Name
  type: String
  required: true
  example: 'ratelimitname'
  description: Specify the name of the parameter.
  cli_alias: name
- name: Value
  type: String
  required: true
  example: 'ratelimitvalue'
  description: Specify the value of the parameter.
  cli_alias: value
